# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.1
_src_path: git+https://github.com/fmi-faim/ipa-project-template
author: Tim-Oliver Buchholz
author_email: tim-oliver.buchholz@fmi.ch
organization: Friedrich Miescher Institute for Biomedical Research
project_name: Dataset Alignment
